### PR TITLE
Put _ast3 and _ast27 in the typed_ast package

### LINKED ISSUE #84: rename the extension modules from toplevel _ast27 and _ast3 into the typed_ast namespace
That's nicer because:
- the package is more self-contained after installation
- the global namespace is less polluted and there's less chance of conflicts with other packages

Follow-up for #18.

### PR DESCRIPTION
**Pull request by ethanhs**
Fixes #84

### CODE REVIEW

**Comment by gvanrossum** [comment]
I don't know how this is supposed to work, but on Mac these imports don't work:
```
from typed_ast import _ast3, _ast27
```
It would seem to me that you have to modify the C source code to really change the module name.

Also I got a merge conflict due to #83.

**Comment by ethanhs** [comment]
@gvanrossum I think you got an old copy of the branch? I fixed the merge conflict before you posted. Also it seems appveyor isn't actually running tests, but I've manually verified this works on Windows. I'm not sure why it isn't working on Mac. Perhaps looking at the folder layout in your site packages will give an indication?

**Comment by msullivan** [comment]
For me it works on OS X when I do a `python3 setup.py build_ext --inplace` but not if I install it

**Comment by msullivan** [comment]
OK I figured out what is going on. This patch *does* work, but things can get fiddly if you install it and then run the tests from the toplevel source directory. If the source directory is on the search path, then `typed_ast` is found in the source directory before it is found in `site-packages`, and python will also expect to find `_ast27` and `_ast3` there, and gets upset.

It also turns out that running `python3 -m pytest` will put the current directory in `sys.path` but running `pytest` doesn't.

So I think this is fine to merge.

We may want to consider reorganizing the directory structure? Though there seem to be annoying tradeoffs with all the different ways to organize a python project directory structure?

**Comment by ethanhs** [comment]
>It also turns out that running python3 -m pytest will put the current directory in sys.path but running pytest doesn't.

This is a feature/the behavior of `python3 -m`, so it is expected.

Glad you figured out the issue.

**Comment by msullivan** [comment]
Oh, though this introduces an inconsistency between the module name and `__module__` in the AST classes, which are still `_ast3`. It looks like we manually populate that field in code generated by `asdl_c.py`, which shouldn't be too hard to fix

**Comment by gvanrossum** [comment]
OK, I see. I was indeed running `python3 -m pytest` from the repo (with `PYTHONPATH` set to point to `build/lib*`). LG then!

**Pull request merged**
