### PR TITLE
[WIP] Automated 3.9 update

### PR DESCRIPTION
**Pull request by ethanhs**
So I automated everything. You can now run `./tools/scripts` to run all of the scripts and commands to do everything step by step. (Well, enough to build anyway, it still has the issues from before).

(Responding to some of your messages from https://github.com/python/typed_ast/pull/137)

>It seems ast.Ellipsis was deprecated and somehow didn't make it into your port? But mypy expects it.

Yeah I noticed that too. It's odd because the ASDL doesn't have the old nodes, but I couldn't figure out how CPython adds it back...

>All that points to deeper problems. Probably it's easier for you.

Hmm, I really have no idea why that would happen. I probably should look more closely at `typed_ast.c`, I am not sure that things get initialized correctly... (I'll look into this tomorrow)

### CODE REVIEW

**Comment by gvanrossum** [comment]
> It's odd because the ASDL doesn't have the old nodes, but I couldn't figure out how CPython adds it back...

CPython has an ast.py in the stdlib (Lib/ast.py) that starts with `from * import _ast` (which imports all the stuff defined in C code), but then adds various compatibility classes like `Ellipsis` and `Bytes` as pure Python classes.

**Comment by ethanhs** [comment]
Ah thanks! somehow I missed that. I'll include that in the files copied.

**Comment by gvanrossum** [comment]
@ethanhs Is this still valuable to you?

**Comment by ethanhs** [comment]
Unfortunately I don't think I will have time to get this to work :/

Maybe I'll pick it up again another time.

**Pull request closed without merging**
