### PR TITLE
ARM64: Add ARM64 jobs in Travis-CI

### PR DESCRIPTION
**Pull request by odidev**
Updated travis.yml file to add ARM64 jobs in Travis-CI. Resolves: #141

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@odidev

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by msullivan** [comment]
This looks good! Thank you.

**Comment by odidev** [comment]
@msullivan Thanks for uploading aarch64 wheel for python3.9. Could you please let me know if there are any plans for releasing aarch64 wheels for python 3.6, 3.7 and 3.8?

**Comment by hauntsaninja** [comment]
I don't know if there are plans, but if someone with PyPI write access sees this, aarch64 wheels are built and ready here: https://console.cloud.google.com/storage/browser/typed-ast

**Comment by gvanrossum** [comment]
I'll do it.

**Comment by gvanrossum** [comment]
Done.

**Pull request merged**
