### PR TITLE
Officially support Python 3.11 (~May 2022)

### PR DESCRIPTION
**Pull request by srittau**

### CODE REVIEW

**Comment by srittau** [comment]
This should probably not go in before the first Python 3.11 beta release (expected May 2022). It fails at the moment anyway, most likely due to missing cibuildwheel support.

**Comment by JelleZijlstra** [comment]
Should we do a release anyway to unblock Python 3.11 testing work? cc @vstinner

**Comment by vstinner** [comment]
> Should we do a release anyway to unblock Python 3.11 testing work? cc @vstinner

Yes please, that would be helpful.

Well, you can still plan the death of the project if you want, but in that case, please help users (like mypy) to migrate to something else ;-) typed_ast seems to be quite popular: https://libraries.io/pypi/typed-ast

* Dependent packages: 277 
* Dependent repositories: 5.18K

**Comment by JelleZijlstra** [comment]
@vstinner for your needs, does it matter whether the release includes wheels for 3.11 and declares support for 3.11 in trove classifiers?

**Comment by vstinner** [comment]
> @vstinner for your needs, does it matter whether the release includes wheels for 3.11 and declares support for 3.11 in trove classifiers?

Oh, I don't care about that :-D All I need is that "python3.11 -m pip install typed_ast" works ;-) You can add it later once Python 3.11 final is released. It's up to you.

**Comment by vstinner** [comment]
>  Build wheels / py311 on windows-latest (pull_request) Failing after 21s — py311 on windows-latest 

For example, Python 3.11 is not supported on your CI yet ;-)

**Comment by hauntsaninja** [comment]
Cool, I can make a release tonight or tomorrow morning (unless someone gets to it first)

**Comment by vstinner** [comment]
Awesome!

**Comment by hauntsaninja** [comment]
Closing for now, since we'll need to upgrade cibuildwheel and maybe walk back the testing added in https://github.com/python/typed_ast/pull/187. Feel free to update and re-open when the time comes.

**Pull request closed without merging**
