### PR TITLE
F-strings!!!

### PR DESCRIPTION
**Pull request by kirbyfan64**
Well, this was a bit more complicated than I thought...

### CODE REVIEW

**Comment by kirbyfan64** [comment]
@ddfisher Bu-uuuuump?

**Comment by ddfisher** [comment]
Sorry for being slow to review this!  I was hoping to get to it this week but had some other things take precedence.  It's at the top of my list for next week!

**Comment by ddfisher** [comment]
This PR has made me realize that the typed_ast update process needs to be nailed down a bit better -- I should have something written up about that shortly, but this PR is blocking on that happening, sorry!

**Comment by JelleZijlstra** [comment]
Any updates here? It would be great to have f-strings supported in mypy before CPython 3.6 final comes out. I can help if necessary.

**Comment by mbdevpl** [comment]
Python 3.6 is here, and...

```
Traceback (most recent call last):
  File "/home/user/Projects/python/typed-astunparse/test/test_unparse.py", line 80, in test_files
    tree = typed_ast.ast35.parse(source=original_code, filename=path)
  File "/home/user/.local/lib/python3.6/site-packages/typed_ast/ast35.py", line 46, in parse
    return _ast35._parse(source, filename, mode)
  File "/home/user/.local/lib/python3.6/functools.py", line 286
    args.extend(f"{k}={v!r}" for (k, v) in self.keywords.items())
                           ^
SyntaxError: invalid syntax
```

What can I do to help?

**Comment by yan12125** [comment]
@mbdevpl I guess you mix 3.5 and 3.6?

**Comment by mbdevpl** [comment]
@yan12125 this PR contains changes to ast35 which actually make it a kind of "ast36" (or some intermediate between 3.5 and 3.6), so after merging this PR the error should disappear... As mentioned in #18 , ast35 might eventually be renamed to ast3.

So, am I really mixing 3.5 and 3.6 here?

**Comment by yan12125** [comment]
functools.py is part of standard Python library and is unrelated to typed_ast. A common reason for syntax error in this file is that you're running the Python 3.5 interpreter and using Python 3.6's library.

How did you run your program?

**Comment by mbdevpl** [comment]
So, first of all, I compiled Python 3.6.0 from source, and installed using `make altinstall` to `~/.local` - just like I did with Python 3.5.2 some time ago. And then I ran  `python3.6 setup.py test`. With `python3.5` my tests pass just like they used to. The test which fails there is about roundtrip parsing and unparsing typed Python ASTs (using typed_ast and typed_astunparse modules).

I think the problem at hand is not that I mix 3.5 and 3.6, but that this PR is still not merged, hence this error. And thus my question, what can I do to help in bringing f-strings to typed_ast?

**Comment by gvanrossum** [comment]
Patience please. See https://github.com/python/mypy/pull/2622

**Comment by mbdevpl** [comment]
@gvanrossum Thank you for that reference. Ok, I'll just wait then.

**Comment by ddfisher** [comment]
Fstrings are now supported.  Sorry for the long wait!  In the process of reviewing this PR, I realized that porting new Python features onto typed_ast was not the best way to go about things, because pull requests like this are difficult to review, and because typed_ast was turning into a mishmash of Python 3.5 and Python 3.6 syntax (both in parsing and in the produced AST).  In lieu of merging this PR, I've instead rebuilt typed_ast on top of the Python 3.6 ast module.  I've also formalized the update process for the future, so there shouldn't be such long waits again (see [here](https://github.com/python/typed_ast/blob/master/update_process.md)).

I appreciate your working in putting up this PR, @kirbyfan64 -- sorry it's not getting landed.

**Comment by santagada** [comment]
no worries, thanks for your work, I can now run mypy again on all my code \o/

**Comment by kirbyfan64** [comment]
I'm just happy that f-strings finally work!! :D

**Pull request closed without merging**
