### PR TITLE
Fix cross compile by adjusting includes

### PR DESCRIPTION
**Pull request by CameronNemo**
Header names conflict with python itself, causing cross compile issues.
This change forces use of in-package header files.

Not sure if this solution is a desirable fix for #134, or if there is a better solution available.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@sgn, @CameronNemo

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by CameronNemo** [comment]
I signed the CLA, but the patch was generated by the script written by @sgn here: https://github.com/void-linux/void-packages/commit/c8a86c3d65f8a150a442ab8968a8c9629eff6aca#diff-6127c099d841ea6775057fe23ea80425R16

**Comment by gvanrossum** [comment]
@mariatta There's some weirdness with the CLA check. When I click on the link [check yourself](https://check-python-cla.herokuapp.com/) and it comes back with

> CameronNemo has signed the CLA ✅
> 
> We will go through the following PRs and remove the CLA not signed label.
> GH-135 Fix cross compile by adjusting includes

But then it re-adds "CLA not signed".

**Comment by Mariatta** [comment]
@gvanrossum the PR contains commits of two people: @CameronNemo  and @sgn . Both users need to sign the CLA. @sgn has not signed.

Alternatively, create a PR containing only @CameronNemo's commit.

**Comment by gvanrossum** [comment]
Thanks @Mariatta, got it!

@sgn mind signing our CLA?

**Comment by sgn** [comment]
Hi, I signed in this page https://www.python.org/psf/contrib/contrib-form/
But the check page still says I haven't signed.

**Comment by Mariatta** [comment]
It can take one-two business days. Please check again later.

**Comment by CameronNemo** [comment]
@sgn make sure you have confirmed via email.

**Comment by sgn** [comment]
On 2020-02-25 17:41:43-0800, Cameron Nemo <notifications@github.com> wrote:
> @sgn make sure you have confirmed via email.

Yes, I've confirmed it and received a pdf file for the CLA.

-- 
Danh

**Comment by sgn** [comment]
The CLA check has accepted my username.

**Comment by gvanrossum** [comment]
Thanks!

**Pull request merged**
