### PR TITLE
Release version 1.5.1

### PR DESCRIPTION
**Pull request by hauntsaninja**

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Thanks for doing the release!

**Comment by hauntsaninja** [comment]
This is done, cc @vstinner :-)

**Comment by vstinner** [comment]
Thank you!

**Comment by vstinner** [comment]
I tested manually and I confirm that it works as expected on the development version of Python 3.11:

```
$ ./python -m venv env   # Python 3.11
$ env/bin/python -m pip install -v typed_ast
(...)
Successfully installed typed-ast-1.5.1
```

**Pull request merged**
