### PR TITLE
Port positional-only arguments from Python 3.8

### PR DESCRIPTION
**Pull request by srittau**
This will enable mypy (and other tools using typed-ast) to parse PEP 570 positional-only arguments in type stubs.

This is not a full backport of Python 3.8 typed-ast, since changes in Python 3.8 (especially the removal of pgen) make this hard.

### CODE REVIEW

**Comment by srittau** [comment]
I am unsure what the problem is. Unfortunately a simple file like

```python
x = 0  # type: int
```

fails with a "misplaced type annotation" error. I suspect that the generated `graminit.c` file is wrong. I tried to regenerate it with the new pgen from Python 3.8, but that has an incompatible definition for at least `dfa`.

**Comment by gvanrossum** [comment]
How did you create the original patch?

The way I had to do it when I created the original 3.7 version of typed_ast was very hacky: IIRC I copied the modified grammar into CPython's 3.7 branch, ran `make regen-grammar` there, and then copied the output files back here. Some details are in step 8 of `update_process.md`.

**Comment by srittau** [comment]
@gvanrossum @msullivan I also needed to use a quite hacky approach. I tried two different methods: I checked out cpython's last commit before removing C pgen. In one approach I modified Parser/token.c to add the `AWAIT` and `ASYNC` tokens (and adjust `N_TOKENS`), since they are present in typed_ast, but not in cpython. In the other approach I left token.c alone and instead modified typed_ast's Grammar file to use literals instead of these tokens. Then I compiled pgen, copied it over to typed_ast and rebuilt it these using the steps from tools/update_ast3_grammar. I needed some manual tweaks (re-adding an `extern` and changing `_Py` to `_Ta3`.

I will play around with this some more today.

**Comment by srittau** [comment]
I can't get this to work, unfortunately.

**Comment by gvanrossum** [comment]
Doesn't look like the end of the world to me. In typeshed we can continue to use the `__varname` convention for positional-only arguments. Thanks for trying!

**Pull request closed without merging**
