### PR TITLE
Test and build wheels on Windows on GitHub Actions

### PR DESCRIPTION
**Pull request by hugovk**
A release for Python 3.9 is currently blocked on AppVeyor adding support:

* https://github.com/appveyor/ci/issues/3541

Hopefully this PR unblocks a Typed AST release.

It runs tests and builds wheels (like `appveyor.yml`) for Python 3.5-3.9 on Windows, and then uploads the wheels as an artifact.

You can see an example run on my fork, plus a link to the wheels zip:

* https://github.com/hugovk/typed_ast/actions/runs/298276469

It contains:

```
typed_ast-1.4.1-cp35-cp35m-win_amd64.whl
typed_ast-1.4.1-cp35-cp35m-win32.whl
typed_ast-1.4.1-cp36-cp36m-win_amd64.whl
typed_ast-1.4.1-cp36-cp36m-win32.whl
typed_ast-1.4.1-cp37-cp37m-win_amd64.whl
typed_ast-1.4.1-cp37-cp37m-win32.whl
typed_ast-1.4.1-cp38-cp38-win_amd64.whl
typed_ast-1.4.1-cp38-cp38-win32.whl
typed_ast-1.4.1-cp39-cp39-win_amd64.whl
typed_ast-1.4.1-cp39-cp39-win32.whl
```

I don't have a Windows machine handy to test them, perhaps someone else could give them a whirl?

### CODE REVIEW

**Comment by gvanrossum** [comment]
What should we do with this one, no #147 has been merged?

**Comment by hugovk** [comment]
It's less urgent, but still an improvement as there's more parallel workers (20) at GitHub Actions compared to AppVeyor (2), and probably more maintainable in the future.

But would prefer someone to check on a Windows machine first. I did a quick test earlier via CI and they installed.

And don't mind if this is closed, happy the 3.9 wheels are now out 👍

**Comment by hugovk** [comment]
Python 3.10 was out last week, it'd be great to get a new release with the Python 3.10 fix (https://github.com/python/typed_ast/pull/158) and with wheels.

AppVeyor will make available Python 3.10 in their next image update. I don't know when that will be; the milestone is 36% complete.

Tracking issue: https://github.com/appveyor/ci/issues/3741
Milestone: https://github.com/appveyor/ci/milestone/95

---

So this PR updated: rebased to include the Python 3.10 fixes, and add `"3.10"` to GitHub Actions.

Example run, built Windows wheels available via the Artifacts at the bottom:

https://github.com/hugovk/typed_ast/actions/runs/1326391177

---

Whilst we're here, we can switch `3.9-dev` on Travis CI to `"3.9"` and add `"3.10-dev`" ([Travis haven't added 3.10 final yet](https://travis-ci.community/t/add-python-3-10/12220)).

**Comment by hauntsaninja** [comment]
Thanks for this! Your PR served as the impetus for me to switch typed_ast to using Github Actions and cibuildwheel for everything in #163

**Pull request closed without merging**
